import random
import string
class User:
    '''
    Class that generates new instances of users
    '''
    def __init__(self,user_name,password):

        self.user_name = user_name
        self.password = password

    user_list = []

    def save_user(self):
        '''
        function to save a new to our list
        '''
        User.user_list.append(self)

    def delete_user(self):
        '''
        function to delete an instance from the list
        '''
        User.user_list.remove(self)

    @classmethod
    def display_user(cls):
        return cls.user_list


class Credential:
    '''
    class that generate new instances of user

    '''
    def __init__( self,site,username,password):

        self.site = site
        self.username = username
        self.password = password
    
    credential_list = []

    def save_credentials(self):
        '''
        method to save a new credential
        '''

        Credential.credential_list.append(self)

    def delete_credential(self):
        '''
        method to delete a  credential
        '''
        
        Credential.credential_list.remove(self)  
    
    @classmethod
    def display_credentials(cls):
        '''
        method to display a  credential
        '''

        return cls.credential_list

    @classmethod
    def find_by_username(cls,number):
        '''
        method to find a  credential by username
        '''

        for credential in cls.credential_list:
            if credential.username == number:
                return credential

    @classmethod
    def do_credential_exist(cls,number):
        '''
        method to check a  credential exists
        '''

        for credential in cls.credential_list:
            if credential.site == number:
                return True
        return False

    def generate_password(passlength=10):
        '''
        method that gives user to use an autogenerated password by the application
        '''

        password = string.ascii_lowercase+ string.ascii_uppercase + string.digits
        return "".join(random.choice(password)  for i in range(passlength))
